### ISSUE TITLE
Czy ten kod jest potrzebny?

### ISSUE THREAD

**Issue by tadeoos** [przytular/chemlab#4]
Czy potrzebujemy z jakiegoś powodu na górze wielu plików fragmentu:
```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
```
czy to jakieś _dobrodziejstwo inwentarza_? :)

**Comment by tadeoos** [comment]
@przytular?

**Comment by wiktoriatomzik** [comment]
https://docs.djangoproject.com/en/1.11/topics/python3/#unicode-literals 

> Performing these changes systematically guarantees backwards compatibility.
> However, Django applications generally don’t need bytestrings, since Django only exposes unicode interfaces to the programmer. Python 3 discourages using bytestrings, except for binary data or byte-oriented interfaces. Python 2 makes bytestrings and unicode strings effectively interchangeable, as long as they only contain ASCII data. Take advantage of this to use unicode strings wherever possible and avoid the b prefixes.

Z tego co tutaj jest napisane jak dla mnie wynika że tak trochę na dwoje babka wróżyła. 

Natomiast tutaj:

https://blog.tankywoo.com/2015/01/21/python-encoding.html

> unicode is no longer exists in Python3.x, because the string type is unicode by default

**Comment by przytular** [comment]
Nie potrzebny, to zaszłość po przejśćiu na Python3. Można wywalić
