### ISSUE TITLE
Polska lokalizacja

### ISSUE THREAD

**Issue by JurekSIN** [przytular/chemlab#6]
Acquired - Nabyto
Origin - Pochodzenie
Region - Region
City - Miasto
Substance - Substancja
Alias - Nazwa produktu
Detected - Wykryto
Observations - Obserwacje
Kinds - Rodzaj
Apperance - Wygląd
Acquired from: Źródło
Color: Kolor
Price: Cena
Test methods: Metody analizy
Search: Szukaj
Show entires: Pokaż wpisów

tekst do wyswietlania boldem powyżej paska z SHOW ENTRIES i SEARCH:

Nasza usługa monitorowania i analiz bezpieczeństwa substancji jest stworzona z myślą o osobach  używających próbek, które trafiają do analizy. Wyniki, które prezentujemy są prawidłowe tylko wtedy, gdy substancja jest identyczna z próbką przebadaną wcześniej. Żaden z naszych wyników nie może zostać użyty jako gwarancja jakości jakiegokolwiek sprzedawcy lub produktu. Społeczna Inicjatywa Narkopolityki nie ponosi żadnej odpowiedzialności w tym zakresie.

**Comment by tadeoos** [comment]
(Jeśli mogę zgłosić feedback do copy)

_Wyniki, które prezentujemy są prawidłowe tylko wtedy, gdy substancja jest identyczna z próbką przebadaną wcześniej._ --> nie bardzo jasne jest dla mnie znaczenie tego zdania :)

**Comment by JurekSIN** [comment]
Wyniki, które prezentujemy odnoszą się jedynie to tej konkretnej substancji, której próbka została przebadana --> tak lepiej?

mozemy to juz postawic ? sory za cisze, zbanowaly mnie skurwysyny

**Comment by JurekSIN** [comment]
Wyniki, które prezentujemy odnoszą się jedynie to tej konkretnej próbki, która została przebadana - może to już nie zostawia zadnej pola do dwuznacznosci ;)

**Comment by przytular** [comment]
Nie bez powodu w projekcie były anglojęzyczne nazwy - w Django lokalizację przeprowadzamy tworząc do tego specjalne pliki dla "tłumacza".

Więcej informacji tutaj
https://docs.djangoproject.com/en/2.0/topics/i18n/translation/

Będzie trzeba cofnąć te zmiany.

**Comment by tadeoos** [comment]
No tak, ale nie musimy tak robić, jeśli docelowo strona ma być w jednym języku (a tak zrozumiałem z gadki z @JurekSIN)
Założyłem, że skoro nie użyłeś w templatce znaczników `{% trans %}` ani  nie używałeś żadnej funkcji 
w `gettext` w modelach etc. to angielskie nazwy były używane właśnie bez powodu ;)

To powiedziawszy nie mam _zasadniczo_ nic przeciwko byśmy zrobili to w zgodzie ze sztuką, choć priorytet temu nadałbym niski. Co więcej trzeba by się wówczas zastanowić nad tłumaczeniem wszystkich treści (vide statyczne stronki) -- to by się związało z dodaniem czegoś w stylu modeltranslation, a to mi zaczyna pachnieć trochę overkillem w przypadku w którym celujemy nasz serwis do polskich odbiorców

**Comment by przytular** [comment]
Chciałbym dodatkowo aby aplikacja mogła byś również wykorzystywana przez podobne organizacje z innych krajów. Ale zgadzam się z Tobą, że nie jest to obecnie priorytet, zostawmy to na póki co na później.
